#%RAML 1.0 Library

traits:
  queryID: !include /Traits/trait.raml
  errorResp: !include /Traits/errorResp.raml
  nameQuery: !include /Traits/nameQuery.raml

types:
    client: !include /DataTypes/client.raml
    phoneId: !include /DataTypes/phoneId.raml
    addresses: !include /DataTypes/addresses.raml

resourceTypes:
  descr: !include /ResourceTypes/resourceType.raml

securitySchemes:
  securityHeader: !include /SecuritySchemes/SecurityClientSecret.raml
  securityClientID: !include /SecuritySchemes/SecurityClientSecret.raml