#%RAML 1.0
title: s-customer-database
version: 1.0
mediaType: application/json

uses:
  common: /Libraries/commonLibrary.raml

securedBy:
  - common.securityClientID

/customers:
    type: common.descr
    get:
      is: [common.queryID,common.nameQuery,common.errorResp]
      responses:
        200:
          body:
            application/json:
              type: common.client
              examples:
                input: !include /Examples/exampleClient.raml
                                                      
    post:
      is: [common.errorResp]
      body:
        application/json:
          type: common.client
          examples:
            input: !include /Examples/exampleClient.json
      responses:
        201:
          body:
            application/json:
              example: !include /Examples/examplePost.json
    /{ID}:
      delete:
        responses:
          200:
            body:
              application/json:
                example:
                  "message": "Klient usunięty z bazy"