#%RAML 1.0 DataType
displayName: Typy danych - dane zamieszkania
type: object
properties:
    city:
      type: string
    postalCode:
      type: string          
    street:
      type: string
    houseNo:
      type: number
    apartmentNo?:
      type: number