#%RAML 1.0 DataType
displayName: Typy danych - info o pracowniku
type: object
properties:
      id:
        type: number
      name:
        type: string
      surname:
        type: string        
      company:
        type: string
      phoneId?:
        type: array
        items:
          type: !include phoneId.raml
      addressId?:
        type: array
        items:
          type: !include addresses.raml
