#%RAML 1.0 SecurityScheme
type: x-token-authorize
description: Dowód tożsamości do zweryfikowania w Headers
describedBy:
  headers:
    authorization:
      type: string
  responses:
    401:
      description: 401-Brak dostępu